[package]
name = "miniproject3-shakespeare"
version = "0.1.0"
authors = ["Olive"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
